config/routes.rb
Rails.application.routes.draw do
  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    resources :products,            only: [:show]
    resources :categories,          only: [:show], param: :taxon_id
    get '/',                        to: 'sample#index'
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  def show
    @taxon = Spree::Taxon.find(params[:taxon_id])
    @root_taxons = Spree::Taxon.roots
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  def index
  end

  def show
    @product = Spree::Product.find(params[:id])
    @related_products = @product.taxons.map{|taxon|taxon.products.where.not(id: @product.id)}.flatten.uniq.sample(4)
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <head>
    <%= render partial: "shared/head" %>
  </head>

  <body>
    <div class="main-wrapper">
      <%= render partial: "shared/header" %>
      <%= render partial: "light_section" %>
      <%= yield %>
      <%= render partial: "shared/footer" %>
      <%= render partial: "shared/copy_right" %>
    </div>
    <%= render partial: "shared/login_modal" %>
    <%= render partial: "shared/signup_modal" %>
    <%= render partial: "shared/product_quick_view_modal" %>
  </body>
</html>

app/views/potepan/categories/_grid_products_view.html.erb
<div class="row">
  <% @taxon.products.each do |product| %>
    <div class="col-sm-4 col-xs-12">
      <div class="productBox">
        <div class="productImage clearfix">
          <%= image_tag product.images.first.attachment.url %>
          <div class="productMasking">
            <ul class="list-inline btn-group" role="group">
              <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
              <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
              <li><a class="btn btn-default" data-toggle="modal" href=".quick-view" ><i class="fa fa-eye"></i></a></li>
            </ul>
          </div>
        </div>
      <%= link_to potepan_product_path(product.id) do %>
        <div class="productCaption clearfix">
          <h5><%= product.name %></h5>
          <h3><%= product.price %></h3>
        </div>
      <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/potepan/categories/_light_section.html.erb
<%# LIGHT SECTION %>
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= @taxon.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <a href="index.html">Home</a>
          </li>
          <li class="active">Single Product</li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/potepan/categories/_list_products_view.html.erb
<div class="row productListSingle">
  <% @taxon.products.each do |product| %>
    <div class="col-xs-12">
      <div class="media">
        <div class="media-left">
          <%= image_tag product.images.first.attachment.url %>
          <span class="maskingImage"><a data-toggle="modal" href=".quick-view" class="btn viewBtn">Quick View</a></span>
        </div>
        <div class="media-body">
          <%= link_to potepan_product_path(product.id) do %>
            <h4 class="media-heading"><%= product.name %></h4>
            <p><%= product.description %></p>
            <h3><%= product.price %></h3>
          <% end %>
          <div class="btn-group" role="group">
            <button type="button" class="btn btn-default" data-toggle="modal" data-target=".login-modal"><i class="fa fa-heart" aria-hidden="true"></i></button>
            <button type="button" class="btn btn-default" onclick="location.href='cart-page.html';"><i class="fa fa-shopping-cart" aria-hidden="true"></i></button>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/potepan/categories/_partners_section.html.erb
<%# LIGHT SECTION %>
<section class="lightSection clearfix">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="owl-carousel partnersLogoSlider">
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-04.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-05.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/categories/show.html.erb
<%# MAIN CONTENT SECTION %>
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-4 col-xs-12 sideBar">
        <div class="panel panel-default">
          <div class="panel-heading">商品カテゴリー</div>
          <div class="panel-body">
            <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
              <ul class="nav navbar-nav side-nav">
                <% @root_taxons.each do |root| %>
                  <li>
                    <a href="javascript:;" data-toggle="collapse" data-target="#<%= root.name %>"><%= root.name %><i class="fa fa-plus"></i></a>
                    <ul id="<%= root.name %>" class="collapse collapseItem">
                      <% root.leaves.each do |leaf| %>
                        <li>
                          <i class="fa fa-caret-right" aria-hidden="true"></i>
                          <%= link_to "#{leaf.name}", potepan_category_path(leaf.id) %><span>(<%= leaf.products.count %>)</span>
                        </li>
                      <% end %>
                    </ul>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
        <div class="panel panel-default priceRange">
          <div class="panel-heading">値段から探す</div>
          <div class="panel-body clearfix">
            <div class="price-slider-inner">
              <span class="amount-wrapper">
                <input type="text" id="price-amount-1" readonly>
                <strong>-</strong>
                <input type="text" id="price-amount-2" readonly>
              </span>
              <div id="price-range"></div>
            </div>
            <input class="btn btn-default" type="submit" value="絞り込む">
            <%# <span class="priceLabel">Price: <strong>12 円- 30<円/strong></span> %>
          </div>
        </div>
        <div class="panel panel-default filterNormal">
          <div class="panel-heading">色から探す</div>
          <div class="panel-body">
            <ul class="list-unstyled">
              <li><a href="#">ブラック<span>(15)</span></a></li>
              <li><a href="#">ホワイト<span>(10)</span></a></li>
              <li><a href="#">レッド<span>(7)</span></a></li>
              <li><a href="#">ブルー<span>(12)</span></a></li>
              <li><a href="#">オレンジ<span>(12)</span></a></li>
            </ul>
          </div>
        </div>
        <div class="panel panel-default filterNormal">
          <div class="panel-heading">サイズから探す</div>
          <div class="panel-body">
            <ul class="list-unstyled clearfix">
              <li><a href="#">S<span>(15)</span></a></li>
              <li><a href="#">M<span>(10)</span></a></li>
              <li><a href="#">L<span>(7)</span></a></li>
              <li><a href="#">XL<span>(12)</span></a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-md-9 col-sm-8 col-xs-12">
        <div class="row filterArea">
          <div class="col-xs-6">
            <select name="guiest_id1" id="guiest_id1" class="select-drop">
              <option value="0">並び替え</option>
              <option value="1">人気順</option>
              <option value="2">安い順</option>
              <option value="3">新着順</option>
              <option value="3">高い順</option>
            </select>
          </div>
          <div class="col-xs-6">
            <div class="btn-group pull-right" role="group">
              <button type="button" class="btn btn-default <%= params[:layout] =="grid" ? "active":""  %>"onclick="window.location.href= '<%= params[:taxon_id] %>?layout=grid'"><i class="fa fa-th" aria-hidden="true"></i><span>Grid</span></button>
              <button type="button" class="btn btn-default <%= params[:layout] =="list" ? "active":""  %>" onclick="window.location.href= '<%= params[:taxon_id]%>?layout=list'"><i class="fa fa-th-list" aria-hidden="true"></i><span>List</span></button>
            </div>
          </div>
        </div>
        <%# ここから商品 %>
        <% case params[:layout] %>
        <% when "list" %>
          <%= render partial: "list_products_view" %>
        <% when "grid" %>
          <%= render partial: "grid_products_view" %>
        <% end %>
        <%# ここまで商品 %>
      </div>
    </div>
  </div>
</section>

<%= render partial: "partners_section" %>

app/views/potepan/products/_light_section.html.erb
<%# LIGHT SECTION %>
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= @product.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <a href="index.html">Home</a>
          </li>
          <li class="active">Single Product</li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/potepan/products/_related_product.html.erb
<div class="col-md-3 col-sm-6 col-xs-12">
  <div class="productBox">
    <div class="productImage clearfix">
      <%= image_tag related_product.images.first.attachment.url %>
      <div class="productMasking">
        <ul class="list-inline btn-group" role="group">
          <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
          <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
          <li><a class="btn btn-default" data-toggle="modal" href=".quick-view" ><i class="fa fa-eye"></i></a></li>
        </ul>
      </div>
    </div>
    <div class="productCaption clearfix">
      <%= link_to potepan_product_path(related_product.id) do %>
       <h5><%= @product.name %></h5>
       <h3><%= @product.price %></h3>
      <% end %>
    </div>
  </div>
</div>

app/views/potepan/products/_related_products_section.html.erb
<div class="row productsContent">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>関連商品</h4>
    </div>
  </div>
  <%= render partial: "related_product", collection: @related_products, locals: { products: @related_products } %>
</div>

app/views/potepan/products/show.html.erb
<%# MAIN CONTENT SECTION %>
<section class="mainContent clearfix">
  <div class="container">
    <div class="row singleProduct">
      <div class="col-xs-12">
        <div class="media">
          <div class="media-left productSlider">
            <div id="carousel" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                <% @product.images.each_with_index do |image, i| %>
                  <div class= "<%= i.zero? ? "item active" : "item" %>" data-thumb="<%=i%>">
                    <%= image_tag (image.attachment.url) %>
                  </div>
                <% end %>
                <%# WIP "RUBY ON RAILS BASEBALL JERSEY"のREDを表示させる %>
              </div>
            </div>
            <div class="clearfix">
              <div id="thumbcarousel" class="carousel slide" data-interval="false">
                <div class="carousel-inner">
                  <% @product.images.each_with_index do |image, i| %>
                    <div data-target="#carousel" data-slide-to="<%=i%>" class="thumb">
                      <%= image_tag (image.attachment.url) %>
                    </div>
                  <% end %>
                </div>
                <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
                  <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
                  <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
              </div>
            </div>
          </div>
          <div class="media-body">
            <ul class="list-inline">
              <li><a href="product_grid_left_sidebar.html"><i class="fa fa-reply" aria-hidden="true"></i>一覧ページへ戻る</a></li>
              <li><a href="#"><i class="fa fa-plus" aria-hidden="true"></i>Share This</a></li>
            </ul>
            <h2><%= @product.name %></h2>
            <h3><%= @product.price %></h3>
            <p><%= @product.description %></p>
            <span class="quick-drop">
              <select name="guiest_id3" id="guiest_id3" class="select-drop">
                <option value="0">S</option>
                <option value="1">M</option>
                <option value="2">L</option>
                <option value="3">XL</option>
              </select>
            </span>
            <span class="quick-drop resizeWidth">
              <select name="guiest_id4" id="guiest_id4" class="select-drop">
              <%#   <option value="0">Qty</option> %>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
              </select>
            </span>
            <div class="btn-area">
              <a href="cart_page.html" class="btn btn-primary btn-block">カートへ入れる<i class="fa fa-angle-right" aria-hidden="true"></i></a>
            </div>
            <div class="tabArea">
              <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#details">details</a></li>
                <li><a data-toggle="tab" href="#about-art">about art</a></li>
                <li><a data-toggle="tab" href="#sizing">sizing</a></li>
                <li><a data-toggle="tab" href="#shipping">shipping</a></li>
              </ul>
              <div class="tab-content">
                <div id="details" class="tab-pane fade in active">
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                  <ul class="list-unstyled">
                    <li>Black, Crew Neck</li>
                    <li>75% Cotton, 25% Rayon</li>
                    <li>Waterbased Ink</li>
                    <li>Wash Cold, dry low</li>
                  </ul>
                </div>
                <div id="about-art" class="tab-pane fade">
                  <p>Nulla facilisi. Mauris efficitur, massa et iaculis accumsan, mauris velit ultrices purus, quis condimentum nibh dolor ut tortor. Donec egestas tortor quis mattis gravida. Ut efficitur elit vitae dignissim volutpat. </p>
                </div>
                <div id="sizing" class="tab-pane fade">
                  <p>Praesent dui felis, gravida a auctor at, facilisis commodo ipsum. Cras eu faucibus justo. Nullam varius cursus nisi, sed elementum sem sagittis at. Nulla tellus massa, vestibulum a commodo facilisis, pulvinar convallis nunc.</p>
                </div>
                <div id="shipping" class="tab-pane fade">
                  <p>Mauris lobortis augue ex, ut faucibus nisi mollis ac. Sed volutpat scelerisque ex ut ullamcorper. Cras at velit quis sapien dapibus laoreet a id odio. Sed sit amet accumsan ante, eu congue metus. Aenean eros tortor, cursus quis feugiat sed, vestibulum vel purus.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <%= render partial: "related_products_section" %>
  </div>
</section>

app/views/shared/_copy_right.html.erb
<%# COPY RIGHT %>
<div class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016 Copyright Bigbag Store Bootstrap Template by <a target="_blank" href="http://www.iamabdus.com/">Abdus</a>.</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
          <li><a href="#"><i class="fa fa-vimeo"></i></a></li>
          <li><a href="#"><i class="fa fa-tumblr"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>
</div>

app/views/shared/_footer.html.erb
<%# FOOTER %>
<div class="footer clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-2 col-xs-12">
        <div class="footerLink">
          <h5>Accessories</h5>
          <ul class="list-unstyled">
            <li><a href="#">Body care </a></li>
            <li><a href="#">Chambray </a></li>
            <li><a href="#">Floral </a></li>
            <li><a href="#">Rejuvination </a></li>
            <li><a href="#">Shaving </a></li>
            <li><a href="#">Toilette </a></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-2 col-xs-12">
        <div class="footerLink">
          <h5>BRANDS</h5>
          <ul class="list-unstyled">
            <li><a href="#">Barbour </a></li>
            <li><a href="#">Brioni </a></li>
            <li><a href="#">Oliver Spencer</a></li>
            <li><a href="#">Belstaff</a></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-2 col-xs-12">
        <div class="footerLink">
          <h5>Accessories</h5>
          <ul class="list-unstyled">
            <li><a href="#">Body care </a></li>
            <li><a href="#">Chambray </a></li>
            <li><a href="#">Floral </a></li>
            <li><a href="#">Rejuvination </a></li>
            <li><a href="#">Shaving </a></li>
            <li><a href="#">Toilette </a></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-2 col-xs-12">
        <div class="footerLink">
          <h5>Get in Touch</h5>
          <ul class="list-unstyled">
            <li>Call us at (555)-555-5555</li>
            <li><a href="mailto:support@iamabdus.com">support@iamabdus.com</a></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-4 col-xs-12">
        <div class="newsletter clearfix">
          <h4>Newsletter</h4>
          <h3>Sign up now</h3>
          <p>Enter your email address and get notified about new products. We hate spam!</p>
          <div class="input-group">
            <input type="text" class="form-control" placeholder="your email address" aria-describedby="basic-addon2">
            <a href="#" class="input-group-addon" id="basic-addon2">go <i class="glyphicon glyphicon-chevron-right"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_head.html.erb
<!DOCTYPE html>
  <head>
    <title>Potepanec</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>

    <%# SITE TITTLE %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>BIGBAG Store</title>

    <%# PLUGINS CSS STYLE %>
    <%= stylesheet_link_tag "application", :media => "all" %>

    <%# GOOGLE FONT %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>
    <%= javascript_include_tag 'application' %>
    <%# CUSTOM CSS %>

    <%# HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries %>
    <%# WARNING: Respond.js doesn't work if you view the page via file:// %>
    <%#[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]%>

  </head>

app/views/shared/_header.html.erb
<%# HEADER %>
<div class="header clearfix">
  <%= render partial: "shared/topbar" %>
  <%= render partial: "shared/navbar" %>
</div>

app/views/shared/_login_modal.html.erb
<%# LOGIN MODAL %>
<div class="modal fade login-modal" id="login" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">log in</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="">Enter Email</label>
            <input type="text" class="form-control" id="">
          </div>
          <div class="form-group">
            <label for="">Password</label>
            <input type="password" class="form-control" id="">
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div>
          <button type="submit" class="btn btn-primary btn-block">log in</button>
          <button type="button" class="btn btn-link btn-block">Forgot Password?</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/shared/_product_quick_view_modal.html.erb
<%# PORDUCT QUICK VIEW MODAL %>
<div class="modal fade quick-view" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <div class="media">
          <div class="media-left">
            <%= image_tag("img/products/quick-view/quick-view-01.jpg", :class => "media-object", :alt => "Image") %>
          </div>
          <div class="media-body">
            <h2>Old Skool Navy</h2>
            <h3>$149</h3>
            <p>Classic sneaker from Vans. Cotton canvas and suede upper. Textile lining with heel stabilizer and ankle support. Contrasting laces. Sits on a classic waffle rubber sole.</p>
            <span class="quick-drop">
              <select name="guiest_id3" id="guiest_id3" class="select-drop">
                <option value="0">Size</option>
                <option value="1">Size 1</option>
                <option value="2">Size 2</option>
                <option value="3">Size 3</option>
              </select>
            </span>
            <span class="quick-drop resizeWidth">
              <select name="guiest_id4" id="guiest_id4" class="select-drop">
                <option value="0">Qty</option>
                <option value="1">Qty 1</option>
                <option value="2">Qty 2</option>
                <option value="3">Qty 3</option>
              </select>
            </span>
            <div class="btn-area">
              <a href="#" class="btn btn-primary btn-block">Add to cart <i class="fa fa-angle-right" aria-hidden="true"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_signup_modal.html.erb
<%# SIGN UP MODAL %>
<div class="modal fade" id="signup" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">Create an account</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="">Enter Email</label>
            <input type="email" class="form-control" id="">
          </div>
          <div class="form-group">
            <label for="">Password</label>
            <input type="password" class="form-control" id="">
          </div>
          <div class="form-group">
            <label for="">Confirm Password</label>
            <input type="password" class="form-control" id="">
          </div>
          <button type="submit" class="btn btn-primary btn-block">Sign up</button>
        </form>
      </div>
    </div>
  </div>
</div>